name: 自动发布npm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # 克隆仓库
      - name: 克隆 master 分支
        uses: actions/checkout@v3

      - name: 安装 node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'

      # 构建
      - name: npm分支自动构建
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        run: |
          ls
          npm i -g pnpm
          pnpm install
          npm run build
          npm run publish-github
